repos:

    - repo: local
      hooks:
        - id: update requirements
          name: update requirements
          entry:  python -m pip install --upgrade -r requirements.txt
          language: system
          always_run: true
          pass_filenames: false
          stages: ["push"]

        - id: test
          name: pytest
          entry: python -m pytest --cov=/app/ --ignore=tests/integration/database
          language: system
          always_run: true
          pass_filenames: false
          
      



