repos:

    - repo: local
      hooks:
        - id: test
          name: pytest
          entry: python -m pytest --cov=/app/ --ignore=tests/integration/database
          language: system
          always_run: true
          pass_filenames: false


